export { default as userRouter } from './user.routes';
export { default as categoryRouter } from './category.routes';
export { default as productRouter } from './product.routes';
export { default as cartRouter } from './cart.routes';
export { default as paymentRouter } from './payment.routes';
export { default as orderRouter } from './order.routes';
export { default as shippingInfoRouter } from './shippingInfo.routes';
export { default as productReviewRouter } from './productReview.routes';
export { default as authRoutes } from './auth.routes';